/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEditItem: typeof import('./src/components/ui/AddEditItem.vue')['default']
    AddItem: typeof import('./src/components/ui/AddItem.vue')['default']
    'AddУвшеItem': typeof import('./src/components/ui/AddУвшеItem.vue')['default']
    AuthForm: typeof import('./src/components/ui/RegisterForm.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DefaultLayout: typeof import('./src/components/layout/DefaultLayout.vue')['default']
    DeleteItem: typeof import('./src/components/ui/DeleteItem.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditItem: typeof import('./src/components/ui/EditItem.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemCard: typeof import('./src/components/ui/ItemCard.vue')['default']
    LoginForm: typeof import('./src/components/ui/LoginForm.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Navbar: typeof import('./src/components/ui/Navbar.vue')['default']
    NumberInputField: typeof import('./src/components/common/NumberInputField.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordField: typeof import('./src/components/common/PasswordField.vue')['default']
    RegisterForm: typeof import('./src/components/ui/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInputField: typeof import('./src/components/common/TextInputField.vue')['default']
    TheWelcome: typeof import('./src/components/ui/TheWelcome.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
