/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    DeferredContent: typeof import('primevue/deferredcontent')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordField: typeof import('./src/components/PasswordField.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    PokemonCartCard: typeof import('./src/components/PokemonCartCard.vue')['default']
    ProductCard: typeof import('./src/components/PokemonCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TextInputField: typeof import('./src/components/TextInputField.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    'ФгерForm': typeof import('./src/components/ФгерForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
