/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    ProductCard: typeof import('./src/components/PokemonCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
